workflows:
  info-and-versions:
    name: Info and Versions
    # instance_type: linux_x2
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
    scripts:
      - name: Run
        script: |
          lscpu
